version: "3.8"

services:
    alita:
        container_name: alita
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            postgresdb:
                condition: service_healthy
            rediscache:
                condition: service_started
        links:
            - postgresdb
            - rediscache
        env_file: alita.env
        restart: always

    rediscache:
        container_name: rediscache
        image: redis:alpine
        restart: always

    postgresdb:
        container_name: postgresdb
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: alita
            POSTGRES_USER: alita
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U alita"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        restart: always